# Generated by gallery/generate.py; do not edit.
# Cell 1: FULL, SIMPLE, and PIECED corner selections
setblock 191 101 205 glassential:stone_glass replace
setblock 192 101 205 glassential:stone_glass replace
setblock 191 102 205 glassential:stone_glass replace
setblock 192 102 205 minecraft:air replace
setblock 195 101 205 glassential:glass_ethereal replace
setblock 196 101 205 glassential:glass_ethereal replace
setblock 195 102 205 glassential:glass_ethereal replace
setblock 196 102 205 minecraft:air replace
setblock 199 101 205 glassential:gravity_glass replace
setblock 200 101 205 glassential:gravity_glass replace
setblock 199 102 205 glassential:gravity_glass replace
setblock 200 102 205 minecraft:air replace
