# Generated by gallery/generate.py; do not edit.
# Cell 2: Pane topology, vertical caps, and mixed-ID boundary
setblock 208 101 204 glassential:glass_ethereal_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 208 101 205 glassential:glass_ethereal_pane[east=false,north=true,south=true,waterlogged=false,west=false] replace
setblock 208 101 206 glassential:glass_ethereal_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 208 102 204 glassential:glass_ethereal_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 208 102 205 glassential:glass_ethereal_pane[east=false,north=true,south=true,waterlogged=false,west=false] replace
setblock 208 102 206 glassential:glass_ethereal_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 212 101 204 glassential:glass_ethereal_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 212 101 205 glassential:glass_ethereal_pane[east=true,north=true,south=false,waterlogged=false,west=false] replace
setblock 213 101 205 glassential:glass_dark_ethereal_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 211 101 209 glassential:glass_ethereal_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
setblock 212 101 208 glassential:glass_ethereal_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 212 101 209 glassential:glass_ethereal_pane[east=true,north=true,south=false,waterlogged=false,west=true] replace
setblock 213 101 209 glassential:glass_ethereal_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 216 101 209 glassential:glass_ethereal_pane[east=true,north=true,south=true,waterlogged=false,west=true] replace
setblock 216 101 208 glassential:glass_ethereal_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 217 101 209 glassential:glass_ethereal_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 216 101 210 glassential:glass_ethereal_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 215 101 209 glassential:glass_ethereal_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
