# Generated by gallery/generate.py; do not edit.
# Cell 3: Bottom, top, double, vertical, and waterlogged slabs
setblock 224 101 206 glassential:glass_slab[type=bottom,waterlogged=false] replace
setblock 225 101 206 glassential:glass_slab[type=bottom,waterlogged=false] replace
setblock 226 101 206 glassential:glass_slab[type=double,waterlogged=false] replace
setblock 228 101 206 glassential:glass_slab[type=top,waterlogged=false] replace
setblock 229 101 206 glassential:glass_slab[type=top,waterlogged=false] replace
setblock 230 101 206 glassential:glass_slab[type=double,waterlogged=false] replace
setblock 232 101 206 glassential:glass_slab[type=top,waterlogged=false] replace
setblock 232 102 206 glassential:glass_slab[type=bottom,waterlogged=false] replace
setblock 232 101 210 glassential:glass_slab[type=bottom,waterlogged=true] replace
