# Generated by gallery/generate.py; do not edit.
# Cell 4: Four colorable routes with exact tint and light behavior
setblock 192 101 222 glassential:colorable_glass[lit=false] replace
data merge block 192 101 222 {Color:16711680,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
setblock 193 101 222 glassential:colorable_glass[lit=true] replace
data merge block 193 101 222 {Color:65535,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
setblock 195 101 222 glassential:colorable_stained_glass[lit=false] replace
data merge block 195 101 222 {Color:65280,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
setblock 196 101 222 glassential:colorable_stained_glass[lit=true] replace
data merge block 196 101 222 {Color:16776960,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
setblock 198 101 222 glassential:colorable_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false,lit=false] replace
data merge block 198 101 222 {Color:8388736,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
setblock 198 101 223 glassential:colorable_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false,lit=true] replace
data merge block 198 101 223 {Color:16744448,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
setblock 200 101 222 glassential:colorable_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false,lit=false] replace
data merge block 200 101 222 {Color:255,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
setblock 200 101 223 glassential:colorable_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false,lit=true] replace
data merge block 200 101 223 {Color:16711935,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b}
