# Generated by gallery/generate.py; do not edit.
# Cell 5: One-way orientation and stock mimic swatches
setblock 208 101 222 glassential:one_way_glass[opaque_face=south] replace
data merge block 208 101 222 {Mimic:"minecraft:stone"}
setblock 208 101 224 minecraft:stone replace
setblock 211 101 222 glassential:one_way_glass[opaque_face=east] replace
data merge block 211 101 222 {Mimic:"minecraft:grass_block"}
setblock 211 101 224 minecraft:grass_block[snowy=false] replace
setblock 214 101 222 glassential:tinted_one_way_glass[opaque_face=up] replace
data merge block 214 101 222 {Mimic:"minecraft:oak_leaves"}
setblock 214 101 224 minecraft:oak_leaves[distance=7,persistent=false,waterlogged=false] replace
setblock 217 101 222 glassential:tinted_one_way_glass[opaque_face=north] replace
data merge block 217 101 222 {Mimic:"minecraft:red_stained_glass"}
setblock 217 101 224 minecraft:red_stained_glass replace
setblock 208 101 226 glassential:one_way_glass[opaque_face=west] replace
data merge block 208 101 226 {Mimic:"not a valid id"}
setblock 208 101 228 minecraft:iron_block replace
