# Generated by gallery/generate.py; do not edit.
# Cell 6: Eighteen vanilla overrides and stock-path controls
setblock 223 101 220 minecraft:glass replace
setblock 225 101 220 minecraft:tinted_glass replace
setblock 227 101 220 minecraft:white_stained_glass replace
setblock 229 101 220 minecraft:orange_stained_glass replace
setblock 231 101 220 minecraft:magenta_stained_glass replace
setblock 233 101 220 minecraft:light_blue_stained_glass replace
setblock 223 101 222 minecraft:yellow_stained_glass replace
setblock 225 101 222 minecraft:lime_stained_glass replace
setblock 227 101 222 minecraft:pink_stained_glass replace
setblock 229 101 222 minecraft:gray_stained_glass replace
setblock 231 101 222 minecraft:light_gray_stained_glass replace
setblock 233 101 222 minecraft:cyan_stained_glass replace
setblock 223 101 224 minecraft:purple_stained_glass replace
setblock 225 101 224 minecraft:blue_stained_glass replace
setblock 227 101 224 minecraft:brown_stained_glass replace
setblock 229 101 224 minecraft:green_stained_glass replace
setblock 231 101 224 minecraft:red_stained_glass replace
setblock 233 101 224 minecraft:black_stained_glass replace
setblock 223 102 220 minecraft:glass replace
setblock 223 101 227 glassential:glass_door[facing=north,half=lower,hinge=left,open=false,powered=false] replace
setblock 223 102 227 glassential:glass_door[facing=north,half=upper,hinge=left,open=false,powered=false] replace
setblock 225 101 227 glassential:glass_trapdoor[facing=north,half=bottom,open=false,powered=false,waterlogged=false] replace
setblock 227 101 227 glassential:glass_glowstone_lamp replace
setblock 229 101 227 glassential:clear_fluid_glass replace
setblock 231 101 227 minecraft:glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] replace
setblock 233 101 227 minecraft:stone replace
