# Generated by gallery/generate.py; do not edit.
scoreboard objectives add gsl_gallery dummy
function glassential_gallery:clear
execute in minecraft:overworld run fill 190 100 202 202 100 214 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 191 100 203 201 100 213 minecraft:smooth_stone replace
execute in minecraft:overworld run function glassential_gallery:cell_build/01_layout_triptych
execute in minecraft:overworld run fill 206 100 202 218 100 214 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 207 100 203 217 100 213 minecraft:smooth_stone replace
execute in minecraft:overworld run function glassential_gallery:cell_build/02_pane_topologies
execute in minecraft:overworld run fill 222 100 202 234 100 214 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 223 100 203 233 100 213 minecraft:smooth_stone replace
execute in minecraft:overworld run function glassential_gallery:cell_build/03_slab_adjacency
execute in minecraft:overworld run fill 190 100 218 202 100 230 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 191 100 219 201 100 229 minecraft:smooth_stone replace
execute in minecraft:overworld run function glassential_gallery:cell_build/04_colorable_blocks
execute in minecraft:overworld run fill 206 100 218 218 100 230 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 207 100 219 217 100 229 minecraft:smooth_stone replace
execute in minecraft:overworld run function glassential_gallery:cell_build/05_one_way_mimics
execute in minecraft:overworld run fill 222 100 218 234 100 230 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 223 100 219 233 100 229 minecraft:smooth_stone replace
execute in minecraft:overworld run function glassential_gallery:cell_build/06_overrides_and_controls
scoreboard players set #cells gsl_gallery 6
scoreboard players set #placements gsl_gallery 80
scoreboard players set #observations gsl_gallery 83
scoreboard players set #ready gsl_gallery 1
function glassential_gallery:verify
