# Generated by gallery/generate.py; do not edit.
scoreboard players set #checked gsl_gallery 0
scoreboard players set #failed_cells gsl_gallery 0
scoreboard players set #failures gsl_gallery 0
execute in minecraft:overworld run function glassential_gallery:cell_verify/01_layout_triptych
execute in minecraft:overworld run function glassential_gallery:cell_verify/02_pane_topologies
execute in minecraft:overworld run function glassential_gallery:cell_verify/03_slab_adjacency
execute in minecraft:overworld run function glassential_gallery:cell_verify/04_colorable_blocks
execute in minecraft:overworld run function glassential_gallery:cell_verify/05_one_way_mimics
execute in minecraft:overworld run function glassential_gallery:cell_verify/06_overrides_and_controls
function glassential_gallery:status
execute if score #failures gsl_gallery matches 0 run tellraw @a {"color":"green","text":"Glassential gallery verification passed."}
execute unless score #failures gsl_gallery matches 0 run tellraw @a {"color":"red","text":"Glassential gallery verification failed."}
