# Generated by gallery/generate.py; do not edit.
# Cell 1: FULL, SIMPLE, and PIECED corner selections
scoreboard players set #case01 gsl_gallery 0
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 191 101 205 glassential:stone_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 192 101 205 glassential:stone_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 191 102 205 glassential:stone_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 192 102 205 minecraft:air run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 195 101 205 glassential:glass_ethereal run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 196 101 205 glassential:glass_ethereal run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 195 102 205 glassential:glass_ethereal run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 196 102 205 minecraft:air run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 199 101 205 glassential:gravity_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 200 101 205 glassential:gravity_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 199 102 205 glassential:gravity_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 200 102 205 minecraft:air run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case01 gsl_gallery 1
execute if score #case01 gsl_gallery matches 1.. run scoreboard players add #failed_cells gsl_gallery 1
execute if score #case01 gsl_gallery matches 1.. run tellraw @a {"color":"red","text":"Glassential gallery cell 1 failed: FULL, SIMPLE, and PIECED corner selections"}
