# Generated by gallery/generate.py; do not edit.
# Cell 3: Bottom, top, double, vertical, and waterlogged slabs
scoreboard players set #case03 gsl_gallery 0
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 224 101 206 glassential:glass_slab[type=bottom,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 225 101 206 glassential:glass_slab[type=bottom,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 226 101 206 glassential:glass_slab[type=double,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 228 101 206 glassential:glass_slab[type=top,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 229 101 206 glassential:glass_slab[type=top,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 230 101 206 glassential:glass_slab[type=double,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 232 101 206 glassential:glass_slab[type=top,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 232 102 206 glassential:glass_slab[type=bottom,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 232 101 210 glassential:glass_slab[type=bottom,waterlogged=true] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case03 gsl_gallery 1
execute if score #case03 gsl_gallery matches 1.. run scoreboard players add #failed_cells gsl_gallery 1
execute if score #case03 gsl_gallery matches 1.. run tellraw @a {"color":"red","text":"Glassential gallery cell 3 failed: Bottom, top, double, vertical, and waterlogged slabs"}
