# Generated by gallery/generate.py; do not edit.
# Cell 4: Four colorable routes with exact tint and light behavior
scoreboard players set #case04 gsl_gallery 0
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 192 101 222 glassential:colorable_glass[lit=false] run scoreboard players set #observation gsl_gallery 1
execute unless data block 192 101 222 {Color:16711680,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 193 101 222 glassential:colorable_glass[lit=true] run scoreboard players set #observation gsl_gallery 1
execute unless data block 193 101 222 {Color:65535,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 195 101 222 glassential:colorable_stained_glass[lit=false] run scoreboard players set #observation gsl_gallery 1
execute unless data block 195 101 222 {Color:65280,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 196 101 222 glassential:colorable_stained_glass[lit=true] run scoreboard players set #observation gsl_gallery 1
execute unless data block 196 101 222 {Color:16776960,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 198 101 222 glassential:colorable_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false,lit=false] run scoreboard players set #observation gsl_gallery 1
execute unless data block 198 101 222 {Color:8388736,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 198 101 223 glassential:colorable_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false,lit=true] run scoreboard players set #observation gsl_gallery 1
execute unless data block 198 101 223 {Color:16744448,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 200 101 222 glassential:colorable_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false,lit=false] run scoreboard players set #observation gsl_gallery 1
execute unless data block 200 101 222 {Color:255,EmitLight:0b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 200 101 223 glassential:colorable_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false,lit=true] run scoreboard players set #observation gsl_gallery 1
execute unless data block 200 101 223 {Color:16711935,EmitLight:1b,EmitRedstone:0b,PassPlayer:0b,PassEntity:0b} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case04 gsl_gallery 1
execute if score #case04 gsl_gallery matches 1.. run scoreboard players add #failed_cells gsl_gallery 1
execute if score #case04 gsl_gallery matches 1.. run tellraw @a {"color":"red","text":"Glassential gallery cell 4 failed: Four colorable routes with exact tint and light behavior"}
