# Generated by gallery/generate.py; do not edit.
# Cell 5: One-way orientation and stock mimic swatches
scoreboard players set #case05 gsl_gallery 0
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 208 101 222 glassential:one_way_glass[opaque_face=south] run scoreboard players set #observation gsl_gallery 1
execute unless data block 208 101 222 {Mimic:"minecraft:stone"} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 208 101 224 minecraft:stone run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 211 101 222 glassential:one_way_glass[opaque_face=east] run scoreboard players set #observation gsl_gallery 1
execute unless data block 211 101 222 {Mimic:"minecraft:grass_block"} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 211 101 224 minecraft:grass_block[snowy=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 214 101 222 glassential:tinted_one_way_glass[opaque_face=up] run scoreboard players set #observation gsl_gallery 1
execute unless data block 214 101 222 {Mimic:"minecraft:oak_leaves"} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 214 101 224 minecraft:oak_leaves[distance=7,persistent=false,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 217 101 222 glassential:tinted_one_way_glass[opaque_face=north] run scoreboard players set #observation gsl_gallery 1
execute unless data block 217 101 222 {Mimic:"minecraft:red_stained_glass"} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 217 101 224 minecraft:red_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 208 101 226 glassential:one_way_glass[opaque_face=west] run scoreboard players set #observation gsl_gallery 1
execute unless data block 208 101 226 {Mimic:"minecraft:iron_block"} run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 208 101 228 minecraft:iron_block run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case05 gsl_gallery 1
execute if score #case05 gsl_gallery matches 1.. run scoreboard players add #failed_cells gsl_gallery 1
execute if score #case05 gsl_gallery matches 1.. run tellraw @a {"color":"red","text":"Glassential gallery cell 5 failed: One-way orientation and stock mimic swatches"}
