# Generated by gallery/generate.py; do not edit.
# Cell 6: Eighteen vanilla overrides and stock-path controls
scoreboard players set #case06 gsl_gallery 0
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 223 101 220 minecraft:glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 225 101 220 minecraft:tinted_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 227 101 220 minecraft:white_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 229 101 220 minecraft:orange_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 231 101 220 minecraft:magenta_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 233 101 220 minecraft:light_blue_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 223 101 222 minecraft:yellow_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 225 101 222 minecraft:lime_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 227 101 222 minecraft:pink_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 229 101 222 minecraft:gray_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 231 101 222 minecraft:light_gray_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 233 101 222 minecraft:cyan_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 223 101 224 minecraft:purple_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 225 101 224 minecraft:blue_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 227 101 224 minecraft:brown_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 229 101 224 minecraft:green_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 231 101 224 minecraft:red_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 233 101 224 minecraft:black_stained_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 223 102 220 minecraft:glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 223 101 227 glassential:glass_door[facing=north,half=lower,hinge=left,open=false,powered=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 223 102 227 glassential:glass_door[facing=north,half=upper,hinge=left,open=false,powered=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 225 101 227 glassential:glass_trapdoor[facing=north,half=bottom,open=false,powered=false,waterlogged=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 227 101 227 glassential:glass_glowstone_lamp run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 229 101 227 glassential:clear_fluid_glass run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 231 101 227 minecraft:glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
scoreboard players add #checked gsl_gallery 1
scoreboard players set #observation gsl_gallery 0
execute unless block 233 101 227 minecraft:stone run scoreboard players set #observation gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #failures gsl_gallery 1
execute if score #observation gsl_gallery matches 1 run scoreboard players add #case06 gsl_gallery 1
execute if score #case06 gsl_gallery matches 1.. run scoreboard players add #failed_cells gsl_gallery 1
execute if score #case06 gsl_gallery matches 1.. run tellraw @a {"color":"red","text":"Glassential gallery cell 6 failed: Eighteen vanilla overrides and stock-path controls"}
